const routes = {
    home: "/",
    signup: "/signup",
    login: "/login",
    wishlist: "/user/wishlist",
    cart: "/user/cart",
    checkout: "/user/checkout",
    singleProduct: "product/:id",
    singleSmartPhone: "smartphone/:id",
    singleLaptop: "laptop/:id",
    singleStudio: "studio/:id",
    singleCamera: "camera/:id",
    singleAccessories: "accessories/:id",
    singlePC: "pc/:id",
    singleTivi: "tivi/:id",
    singlePromotion: "promotion/:id",
    checkOut: "user/checkout",
    smartphone: "smartphone",
    laptop: "laptop",
    studio: "studio",
    camera: "camera",
    accessories: "accessories",
    pc: "pc",
    tivi: "tivi",
    promotion: "promotion",
    member: 'member',
}

export default routes
